export const EditorCompletionItemHighlight = 'EditorCompletionItemHighlight'
export const Label = 'Label'
export const ScrollBar = 'ScrollBar'
export const ScrollBarSmall = 'ScrollBarSmall'
export const ScrollBarThumb = 'ScrollBarThumb'
